### ISSUE TITLE
Keypress outputs double characters

### ISSUE THREAD

**Issue by Sasatari** [atarimacosx/Atari800MacX#16] opened 2020-05-19 16:00 UTC
When typing certain keys, additionally to the chosen character with some characters there appears an unwanted extra character, which has to be deleted. That makes typing, especially coding really frustrating.

For example if you press '"' it outputs '"@"
If you press ':' it outputs ':>'
If you press ';' it outputs ';<'

**Comment by pedgarcia** [comment] 2020-05-19 17:36
Hey @Sasatari , I am not able to reproduce the issue. I wonder if there is something with the configuration causing this.v. Based on what you say, it is not using a specific program, right? It happens all the time...

Not sure if you can share the configuration you are using, maybe focusing on atari type, controllers tab, gamepads etc.

You could also save your configuration and share the file with us...

**Comment by markgrebe** [comment] 2020-05-20 01:37
@Sasatari, I agree with Paulo, I don't have the issue here, and I suspect it's configuration.  You can save one for us, or just send us your ~/Library/Preferences/com.atarimac.atari800macx.plist file.  You could also rename it with the emulator not running, and it should recreate it when you run the emulator and see if you have the issue then.  (You would loose your settings with that, but you could delete the new one, and rename the old one back).

**Comment by Sasatari** [comment] 2020-05-20 06:52
Thanks for picking this up.
At the ABBUC Forums there is another German user having that issue. So it might be language related. But I couldn´t find any setting, where this doesn´t happen.
Please find attached my plist-file (zipped) and a Screenshot where I pressed some keys without shift, and the with shift. Somehow the Shift-Key seems to be involved.

[com.atarimac.atari800macx.plist.zip](https://github.com/atarimacosx/Atari800MacX/files/4655065/com.atarimac.atari800macx.plist.zip)
![keypresses](https://user-images.githubusercontent.com/17954889/82414166-ea8aba00-9a76-11ea-8883-e074335a7e32.jpg)

**Comment by atarimacosx** [comment] 2020-05-21 01:37
@Sasatari, this is an issue with non-US keyboard configurations, I didn't have any issue repeating it when I set the keyboard input to German.  This has actually been there since the 5.0.0 release, and is an easy 4 line fix.   I'm attaching a Zip of a beta for the application.  Please see if it fixes the issue for you (I'm pretty confident it will), and if it does, I will do a real 5.0.3 release.

Danke, dass Sie dies gemeldet haben,
Mark
[Atari800MacX.zip](https://github.com/atarimacosx/Atari800MacX/files/4660164/Atari800MacX.zip)

**Comment by Sasatari** [comment] 2020-05-21 10:18
@markgrebe: This was a big issue for Florian D., and he just sent me this:

<img width="1005" alt="great" src="https://user-images.githubusercontent.com/17954889/82549330-12544d80-9b5d-11ea-9679-7f6e501e7c73.png">

Also many thanks from me. Great work!

**Comment by atarimacosx** [comment] 2020-05-22 00:28
Glad to hear everything is working!

I'm closing the issue, I just posted the 5.0.3 release.

**Closed by atarimacosx** 2020-05-22 00:28 UTC
